apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-rec-sys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-rec-sys
  template:
    metadata:
      labels:
        app: anime-rec-sys
    spec:
      containers:
      - name: anime-rec-sys-container
        image: gcr.io/anime-rec-sys/anime-nexus:latest
        ports:
        - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  name: anime-rec-sys-service
spec:
  type: LoadBalancer
  selector:
    app: ml-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000



